version: "3.8"

services:
  db:
    image: postgres:15
    container_name: karib-postgres
    environment:
      POSTGRES_USER: karib
      POSTGRES_PASSWORD: karib_pass
      POSTGRES_DB: karibmarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
